Task-AQL17-edit column table for show data in app
ctnet-tech/easysalon-app-ui-kit pull request #4
Opened 2021-07-07 07:22 UTC by nguyenphuochai1998

2021-07-09 06:45 UTC, NguyenQuangKhang approved these changes

2021-07-12 02:11 UTC, nguyenphuochai1998 reviewed
check fist it ok

2021-07-12 02:12 UTC, nguyenphuochai1998 reviewed
check fist have many space text

2021-07-13 02:40 UTC, NguyenQuangKhang requested changes

2021-07-13 02:40 UTC, NguyenQuangKhang commented on lib/widgets/basic/data_table.dart
> +import 'package:easysalon_mobile_ui_kit/services/layout_notifier.dart';
config Size của các Column

2021-07-13 02:45 UTC, NguyenQuangKhang requested changes

2021-07-13 02:45 UTC, NguyenQuangKhang commented on lib/widgets/basic/data_table.dart
> +      {Key? key,
thêm custom size cho các Column

2021-07-15 09:18 UTC, closed without merging